spring:
  application:
    name: tbd
  datasource:
    url: jdbc:postgresql://ep-sweet-queen-aet1x7oq-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_fd97WYNIkHMJ
  jpa:
    hibernate:
      ddl-auto: none    # Changed from 'create' to 'none' to prevent table recreation
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: bikersdream
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true     # Added to see the SQL queries being executed
  flyway:
    enabled: true
    locations: classpath:db/migration
    defaultSchema: bikersdream
    baseline-on-migrate: true

logging:
  level:
    com.soen343.tbd: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.pool.HikariPool: WARN

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    